.TH FASTFETCH 1  "Sep 23 2025" "Fastfetch 2.53.0" "FASTFETCH"
.SH NAME
fastfetch \- A fast and feature-rich system information tool similar to neofetch
.SH SYNOPSIS
.B fastfetch
[\fIOPTIONS\fR...]
.SH DESCRIPTION

Fastfetch is a tool for displaying system information in a visually appealing way. Written primarily in C, it focuses on performance and customizability while providing functionality similar to neofetch.
It supports Linux, Android, FreeBSD, macOS, and Windows 7 or newer.

.SH CONFIGURATION

.SS Fetch Structure

The structure defines which modules to display and in what order. It consists of module names separated by colons (:).
For example: \fBtitle:separator:os:kernel:uptime\fR

To list all available modules, use \fB--list-modules\fR


.SS Config Files

Fastfetch uses JSONC (JSON with Comments) for configuration files. These files must have the .jsonc extension.

You can generate a default config file using \fB--gen-config\fR. By default, the config file is saved at \fB~/.config/fastfetch/config.jsonc\fR.

The configuration/preset files are searched in the following locations (in order):

\fB1.\fR Relative to the current working directory

\fB2.\fR Relative to ~/.local/share/fastfetch/presets/

\fB3.\fR Relative to /usr/share/fastfetch/presets/

For detailed information on logo options, module configuration, and formatting, visit:
\fBhttps://github.com/fastfetch-cli/fastfetch/wiki/Configuration\fR

Fastfetch provides several built-in presets. List them with \fB--list-presets\fR.

.SS JSON Schema
A JSON schema is available for editor intelligence when editing the configuration file. Add the following line at the beginning of your config file:

\fB"$schema": "https://github.com/fastfetch-cli/fastfetch/raw/dev/doc/json_schema.json"\fR

.SH OPTIONS

Options are parsed in a case-insensitive manner. For example, \fB--logo-type\fR and \fB--LOGO-TYPE\fR are treated identically.

Arguments in square brackets are optional. Optional boolean arguments default to 'true' when specified without a value.

For more detailed information about a specific option, use:
\fBfastfetch -h <option_name_without_dashes>\fR

Any combination of options can be made permanent by generating a configuration file:
\fBfastfetch <options> --gen-config\fR


.SS Informative
.TP
\fB\-h, \-\-help\fR [\fIcommand\fR]
 Display this help message or help for a specific command

.TP
\fB\-v, \-\-version\fR 
 Show the full version of fastfetch

.TP
\fB\-\-version-raw\fR 
 Display the raw version string (major.minor.patch)

.TP
\fB\-\-list-config-paths\fR 
 List search paths for config files

.TP
\fB\-\-list-data-paths\fR 
 List search paths for presets and logos

.TP
\fB\-\-list-logos\fR 
 List available logos

.TP
\fB\-\-list-modules\fR 
 List available modules

.TP
\fB\-\-list-presets\fR 
 List presets that fastfetch knows about

 Presets can be loaded with "--config <preset-name>"

.TP
\fB\-\-list-features\fR 
 List the supported features that fastfetch was compiled with

 Mainly for development

.TP
\fB\-\-print-logos\fR 
 Display available logos

.TP
\fB\-\-print-structure\fR 
 Display the default structure

.TP
\fB\-\-format\fR \fIenum\fR
 Set output format

.SS Config
.TP
\fB\-c, \-\-config\fR \fIconfig\fR
 Specify the config file or preset to load

 The file will be searched according to the order shown by "fastfetch --list-config-paths". Use "none" to disable further config loading. See also https://github.com/fastfetch-cli/fastfetch/wiki/Configuration for more info

.TP
\fB\-\-gen-config\fR [\fIpath\fR]
 Generate a minimal config file at the specified path

 Defaults to "~/.config/fastfetch/config.jsonc". Will print the generated config if <path> is "-"

.TP
\fB\-\-gen-config-full\fR [\fIpath\fR]
 Generate a full config file with all optional options at the specified path

 Defaults to "~/.config/fastfetch/config.jsonc". Will print the generated config if <path> is "-"

.TP
\fB\-\-gen-config-force\fR [\fIpath\fR]
 Generate a config file at the specified path, overwriting any existing file

 Defaults to "~/.config/fastfetch/config.jsonc"

.SS General
.TP
\fB\-\-thread\fR [\fIbool\fR]
 Use separate threads for HTTP requests

.TP
\fB\-\-wmi-timeout\fR \fInum\fR
 Set the timeout (ms) for WMI queries

 Windows only

.TP
\fB\-\-processing-timeout\fR \fInum\fR
 Set the timeout (ms) when waiting for child processes

.TP
\fB\-\-ds-force-drm\fR [\fIenum\fR]
 Specify whether only DRM should be used to detect displays

 Use this option if you encounter problems with other detection methods.
 Linux only

.TP
\fB\-\-detect-version\fR [\fIbool\fR]
 Specify whether to detect and display versions of terminal, shell, editor, and others

 Mainly for benchmarking

.SS Logo
.TP
\fB\-l, \-\-logo\fR \fIlogo\fR
 Set the logo source. Use "none" to disable the logo

 Should be the name of a built-in logo or a path to an image file. See also https://github.com/fastfetch-cli/fastfetch/wiki/Logo-options

.TP
\fB\-\-logo-type\fR \fIenum\fR
 Set the type of the logo specified in "--logo"

 See also https://github.com/fastfetch-cli/fastfetch/wiki/Logo-options

.TP
\fB\-\-logo-width\fR \fInum\fR
 Set the width of the logo (in characters) if it is an image

 Required for iTerm image protocol

.TP
\fB\-\-logo-height\fR \fInum\fR
 Set the height of the logo (in characters) if it is an image

 Required for iTerm image protocol

.TP
\fB\-\-logo-preserve-aspect-ratio\fR [\fIbool\fR]
 Specify whether the logo should fill the specified width and height as much as possible without stretching

 Supported by iTerm image protocol only

.TP
\fB\-\-logo-color-[1-9]\fR \fIcolor\fR
 Override a color in the logo

 See `-h color` for the list of available colors

.TP
\fB\-\-logo-padding\fR \fInum\fR
 Set the padding on the left and right sides of the logo

.TP
\fB\-\-logo-padding-left\fR \fInum\fR
 Set the padding on the left side of the logo

.TP
\fB\-\-logo-padding-right\fR \fInum\fR
 Set the padding on the right side of the logo

.TP
\fB\-\-logo-padding-top\fR \fInum\fR
 Set the padding at the top of the logo

.TP
\fB\-\-logo-print-remaining\fR [\fIbool\fR]
 Specify whether to print the remaining logo if it has more lines than modules to display

.TP
\fB\-\-logo-position\fR \fIenum\fR
 Set the position where the logo should be displayed

.TP
\fB\-\-logo-recache\fR [\fIbool\fR]
 If true, regenerate the image logo cache

.TP
\fB\-\-file\fR \fIpath\fR
 Short for --logo-type file --logo <path>

 See "--help logo-type" for more info

.TP
\fB\-\-file-raw\fR \fIpath\fR
 Short for --logo-type file-raw --logo <path>

 See "--help logo-type" for more info

.TP
\fB\-\-data\fR \fIdata\fR
 Short for --logo-type data --logo <data>

 See "--help logo-type" for more info

.TP
\fB\-\-data-raw\fR \fIdata\fR
 Short for --logo-type data-raw --logo <data>

 See "--help logo-type" for more info

.TP
\fB\-\-raw\fR \fIpath\fR
 Short for --logo-type raw --logo <path>

 See "--help logo-type" for more info

.TP
\fB\-\-sixel\fR \fIpath\fR
 Short for --logo-type sixel --logo <path>

 See "--help logo-type" for more info

.TP
\fB\-\-kitty\fR \fIpath\fR
 Short for --logo-type kitty --logo <path>

 See "--help logo-type" for more info

.TP
\fB\-\-kitty-direct\fR \fIpath\fR
 Short for --logo-type kitty-direct --logo <path>

 See "--help logo-type" for more info

.TP
\fB\-\-kitty-icat\fR \fIpath\fR
 Short for --logo-type kitty-icat --logo <path>

 See "--help logo-type" for more info

.TP
\fB\-\-iterm\fR \fIpath\fR
 Short for --logo-type iterm --logo <path>

 See "--help logo-type" for more info

.TP
\fB\-\-chafa\fR \fIpath\fR
 Short for --logo-type chafa --logo <path>

 See "--help logo-type" for more info

.TP
\fB\-\-chafa-fg-only\fR [\fIbool\fR]
 Produce character-cell output using foreground colors only

 See chafa document for detail

.TP
\fB\-\-chafa-symbols\fR \fIstr\fR
 Specify character symbols to employ in final output

 See chafa document for detail

.TP
\fB\-\-chafa-canvas-mode\fR \fIenum\fR
 Determine how colors are used in the output

 This value maps the int value of enum ChafaCanvasMode. See chafa document for detail

.TP
\fB\-\-chafa-color-space\fR \fIenum\fR
 Set color space used for quantization

 This value maps the int value of enum ChafaColorSpace. See chafa document for detail

.TP
\fB\-\-chafa-dither-mode\fR \fIenum\fR
 Set output dither mode (No effect with 24-bit color)

 This value maps the int value of enum ChafaDitherMode. See chafa document for detail

.SS Display
.TP
\fB\-s, \-\-structure\fR \fIstructure\fR
 Set the structure of the fetch

 Must be a colon-separated list of keys. Use "fastfetch --list-modules" to see available options

.TP
\fB\-\-stat\fR [\fIbool\fR]
 Show time usage (in ms) for individual modules

.TP
\fB\-\-pipe\fR [\fIbool\fR]
 Disable colors

 Auto-detected based on isatty(1) by default

.TP
\fB\-\-color\fR \fIcolor\fR
 Set the color of both keys and title

 Shortcut for "--color-keys <color>" and "--color-title <color>"
 For color syntax, see <https://github.com/fastfetch-cli/fastfetch/wiki/Color-Format-Specification>

.TP
\fB\-\-color-keys\fR \fIcolor\fR
 Set the color of the keys

 Doesn't affect Title, Separator, and Colors modules. See `-h color` for the list of available colors

.TP
\fB\-\-color-title\fR \fIcolor\fR
 Set the color of the title

 See `-h color` for the list of available colors

.TP
\fB\-\-color-output\fR \fIcolor\fR
 Set the color of module output

 See `-h color` for the list of available colors

.TP
\fB\-\-color-separator\fR \fIcolor\fR
 Set the color of the key-value separator

 See `-h color` for the list of available colors

.TP
\fB\-\-duration-abbreviation\fR [\fIbool\fR]
 Specify whether to abbreviate duration values

 If true, the output will be in the form of "1h 2m" instead of "1 hour, 2 mins"

.TP
\fB\-\-duration-space-before-unit\fR \fIenum\fR
 Specify whether to put a space before the unit in duration values

.TP
\fB\-\-key-width\fR \fInum\fR
 Align the width of keys to <num> characters

.TP
\fB\-\-key-padding-left\fR \fInum\fR
 Set the left padding of keys to <num> characters

.TP
\fB\-\-key-type\fR \fIenum\fR
 Specify whether to show an icon before string keys

.TP
\fB\-\-bright-color\fR [\fIbool\fR]
 Specify whether keys, title, and ASCII logo should be printed in bright color

.TP
\fB\-\-separator\fR \fIstr\fR
 Set the separator between key and value

.TP
\fB\-\-show-errors\fR [\fIbool\fR]
 Print errors when they occur

.TP
\fB\-\-disable-linewrap\fR [\fIbool\fR]
 Specify whether to disable line wrap during execution

.TP
\fB\-\-hide-cursor\fR [\fIbool\fR]
 Specify whether to hide the cursor during execution

.TP
\fB\-\-percent-type\fR \fInum\fR
 Set the percentage output type

 1 for percentage number
 2 for multi-color bar
 3 for both
 6 for bar only
 9 for colored number
 10 for monochrome bar

.TP
\fB\-\-percent-ndigits\fR \fInum\fR
 Set the number of digits to keep after the decimal point when formatting percentage numbers

.TP
\fB\-\-percent-color-green\fR \fIcolor\fR
 Set color used for the green state of percentage bars and numbers

 See `-h color` for the list of available colors

.TP
\fB\-\-percent-color-yellow\fR \fIcolor\fR
 Set color used for the yellow state of percentage bars and numbers

 See `-h color` for the list of available colors

.TP
\fB\-\-percent-color-red\fR \fIcolor\fR
 Set color used for the red state of percentage bars and numbers

 See `-h color` for the list of available colors

.TP
\fB\-\-percent-space-before-unit\fR \fIenum\fR
 Specify whether to put a space before the percentage symbol

.TP
\fB\-\-percent-width\fR \fInum\fR
 Specify the width of the percentage number, in number of characters

 This option affects only percentage numbers, not bars

.TP
\fB\-\-bar-char-elapsed\fR \fIstr\fR
 Set the character to use in the elapsed part of percentage bars

.TP
\fB\-\-bar-char-total\fR \fIstr\fR
 Set the character to use in the total part of percentage bars

.TP
\fB\-\-bar-border-left\fR \fIstring\fR
 Set the string to use at the left border of percentage bars

.TP
\fB\-\-bar-border-right\fR \fIstring\fR
 Set the string to use at the right border of percentage bars

.TP
\fB\-\-bar-border-left-elapsed\fR \fIstring\fR
 If both bar-border-left-elapsed and bar-border-right-elapsed are set, the border will be used as parts of bar content

.TP
\fB\-\-bar-border-right-elapsed\fR \fIstring\fR
 If both bar-border-left-elapsed and bar-border-right-elapsed are set, the border will be used as parts of bar content

.TP
\fB\-\-bar-color-elapsed\fR \fIcolor\fR
 Set the color to use in the elapsed part of percentage bars

 By default, auto selected by percent-color-{green,yellow,red}

.TP
\fB\-\-bar-color-total\fR \fIcolor\fR
 Set the color to use in the total part of percentage bars

.TP
\fB\-\-bar-color-border\fR \fIcolor\fR
 Set the color to use in the borders of percentage bars

.TP
\fB\-\-bar-width\fR \fInum\fR
 Set the width of percentage bars in characters

.TP
\fB\-\-no-buffer\fR [\fIbool\fR]
 Specify whether the stdout application buffer should be disabled

.TP
\fB\-\-size-ndigits\fR \fInum\fR
 Set the number of digits to keep after the decimal point when formatting sizes

.TP
\fB\-\-size-binary-prefix\fR \fIenum\fR
 Set the binary prefix to use when formatting sizes

.TP
\fB\-\-size-max-prefix\fR \fIenum\fR
 Set the largest binary prefix to use when formatting sizes

.TP
\fB\-\-size-space-before-unit\fR \fIenum\fR
 Specify whether to put a space before the unit

.TP
\fB\-\-freq-ndigits\fR \fInum\fR
 Set the number of digits to keep after the decimal point when printing CPU/GPU frequency in GHz

.TP
\fB\-\-freq-space-before-unit\fR \fIenum\fR
 Specify whether to put a space before the unit

.TP
\fB\-\-fraction-ndigits\fR \fInum\fR
 Set the number of digits to keep after the decimal point when printing ordinary fraction numbers

 If negative, the number of digits will be automatically determined based on the value

.TP
\fB\-\-fraction-trailing-zeros\fR \fIenum\fR
 Set when to keep trailing zeros

.TP
\fB\-\-temp-unit\fR \fIenum\fR
 Set the temperature unit

.TP
\fB\-\-temp-ndigits\fR \fInum\fR
 Set the number of digits to keep after the decimal point when printing temperature

.TP
\fB\-\-temp-color-green\fR \fIcolor\fR
 Set color used for the green state of temperature values

 See `-h color` for the list of available colors

.TP
\fB\-\-temp-color-yellow\fR \fIcolor\fR
 Set color used for the yellow state of temperature values

 See `-h color` for the list of available colors

.TP
\fB\-\-temp-color-red\fR \fIcolor\fR
 Set color used for the red state of temperature values

 See `-h color` for the list of available colors

.TP
\fB\-\-temp-space-before-unit\fR \fIenum\fR
 Specify whether to put a space before the unit

.SH EXAMPLES

.SS Basic Usage
\fBfastfetch\fR

.SS Use a specific logo
\fBfastfetch --logo arch\fR

.SS Custom structure
\fBfastfetch --structure title:os:kernel:uptime:memory\fR

.SS Generate a config file
\fBfastfetch --gen-config\fR

.SS Use a preset
\fBfastfetch --config neofetch\fR

.SS Config File Example
.nf
// ~/.config/fastfetch/config.jsonc
{
    "$schema": "https://github.com/fastfetch-cli/fastfetch/raw/dev/doc/json_schema.json",
    "logo": {
        "type": "auto",
        "source": "arch"
    },
    "display": {
        "separator": ": ",
        "color": {
            "keys": "blue",
            "title": "red"
        },
        "key": {
            "width": 12
        }
    },
    "modules": [
        "title",
        "separator",
        "os",
        "kernel",
        "uptime",
        {
            "type": "memory",
            "format": "{used}/{total} ({used_percent}%)"
        }
    ]
}
.fi

.SH "SEE ALSO"
.BR neofetch (1)
.SH BUGS
Please report bugs to: https://github.com/fastfetch-cli/fastfetch/issues
.SH AUTHORS
Fastfetch is developed by a team of contributors on GitHub.
Visit https://github.com/fastfetch-cli/fastfetch for more information.
